### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by master7720** [DriftyDev/CLEAN_Kami5-1.8-BUILDABLE_SRC#4]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/8/21 3:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tech.mmmax.kami.api.utils.render.RenderUtil.addBuilderVertex(RenderUtil.java:183)
	at tech.mmmax.kami.api.utils.render.RenderUtil.buildBBBuffer(RenderUtil.java:96)
	at tech.mmmax.kami.api.utils.render.RenderUtil.renderBB(RenderUtil.java:59)
	at tech.mmmax.kami.impl.features.modules.render.HoleEsp.onRender3d(HoleEsp.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_HoleEsp_onRender3d_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1432)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at tech.mmmax.kami.api.utils.render.RenderUtil.addBuilderVertex(RenderUtil.java:183)
	at tech.mmmax.kami.api.utils.render.RenderUtil.buildBBBuffer(RenderUtil.java:96)
	at tech.mmmax.kami.api.utils.render.RenderUtil.renderBB(RenderUtil.java:59)
	at tech.mmmax.kami.impl.features.modules.render.HoleEsp.onRender3d(HoleEsp.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_HoleEsp_onRender3d_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1432)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 13 total; [EntityPlayerSP['PreparedSystem32'/600596, l='MpServer', x=-15.55, y=4.73, z=-15.13], EntityOtherPlayerMP['0rthrus'/570892, l='MpServer', x=1.57, y=122.00, z=0.67], EntityOtherPlayerMP['Ratdogg'/593905, l='MpServer', x=4.61, y=4.00, z=8.33], EntityOtherPlayerMP['Kildrio'/407987, l='MpServer', x=28.88, y=121.00, z=11.96], EntityOtherPlayerMP['AnvilFag'/599828, l='MpServer', x=6.67, y=3.29, z=6.47], EntityOtherPlayerMP['crys5al'/599654, l='MpServer', x=-0.37, y=121.00, z=-20.74], EntityOtherPlayerMP['unluckyGG'/581671, l='MpServer', x=20.68, y=3.00, z=-12.60], EntityOtherPlayerMP['Beretta3'/599665, l='MpServer', x=23.69, y=2.00, z=-13.30], EntityOtherPlayerMP['zNeuX1'/599639, l='MpServer', x=-19.28, y=121.00, z=11.22], EntityOtherPlayerMP['xy2k'/598977, l='MpServer', x=32.50, y=3.00, z=-30.50], EntityOtherPlayerMP['BigHomieBruh'/593754, l='MpServer', x=16.76, y=122.01, z=25.81], EntityOtherPlayerMP['P3nisPro'/601265, l='MpServer', x=0.07, y=122.00, z=4.52], EntityOtherPlayerMP['wallsfree'/601267, l='MpServer', x=-0.10, y=122.00, z=1.33]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,122,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 65914 game time, 14500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityPlayerSP['PreparedSystem32'/600596, l='MpServer', x=-15.55, y=4.73, z=-15.13], EntityOtherPlayerMP['P3nisPro'/601265, l='MpServer', x=0.07, y=122.00, z=4.52], EntityOtherPlayerMP['0rthrus'/570892, l='MpServer', x=1.57, y=122.00, z=0.67], EntityOtherPlayerMP['wallsfree'/601267, l='MpServer', x=-0.10, y=122.00, z=1.33], EntityOtherPlayerMP['Ratdogg'/593905, l='MpServer', x=4.61, y=4.00, z=8.33], EntityOtherPlayerMP['0rthrus'/570892, l='MpServer', x=1.57, y=122.00, z=0.67], EntityOtherPlayerMP['bbedwars'/576353, l='MpServer', x=0.93, y=122.00, z=2.20], EntityOtherPlayerMP['Kildrio'/407987, l='MpServer', x=28.88, y=121.00, z=11.96], EntityExpBottle['entity.ThrownExpBottle.name'/601295, l='MpServer', x=32.85, y=3.88, z=-30.30], EntityOtherPlayerMP['AnvilFag'/599828, l='MpServer', x=6.67, y=3.29, z=6.47], EntityEnderCrystal['entity.EnderCrystal.name'/601294, l='MpServer', x=3.50, y=4.00, z=8.50], EntityOtherPlayerMP['crys5al'/599654, l='MpServer', x=-0.37, y=121.00, z=-20.74], EntityOtherPlayerMP['xy2k'/598977, l='MpServer', x=32.50, y=3.00, z=-30.50], EntityOtherPlayerMP['unluckyGG'/581671, l='MpServer', x=20.68, y=3.00, z=-12.60], EntityOtherPlayerMP['Beretta3'/599665, l='MpServer', x=23.69, y=2.00, z=-13.30], EntityOtherPlayerMP['zNeuX1'/599639, l='MpServer', x=-19.28, y=121.00, z=11.22], EntityOtherPlayerMP['BigHomieBruh'/593754, l='MpServer', x=9.78, y=3.00, z=-33.47], EntityOtherPlayerMP['ezp0p'/584622, l='MpServer', x=33.28, y=2.00, z=-30.41], EntityOtherPlayerMP['4783'/596210, l='MpServer', x=2.08, y=5.00, z=-45.21], EntityOtherPlayerMP['4783'/596210, l='MpServer', x=33.32, y=3.00, z=-34.45], EntityOtherPlayerMP['bbedwars'/576353, l='MpServer', x=31.37, y=3.00, z=-34.25], EntityOtherPlayerMP['xy2k'/598977, l='MpServer', x=32.50, y=3.00, z=-30.50], EntityOtherPlayerMP['BigHomieBruh'/593754, l='MpServer', x=16.76, y=122.01, z=25.81], EntityOtherPlayerMP['AnvilFag'/599828, l='MpServer', x=6.67, y=3.29, z=6.47], EntityOtherPlayerMP['zNeuX1'/599639, l='MpServer', x=-19.28, y=121.00, z=11.22], EntityOtherPlayerMP['BigHomieBruh'/593754, l='MpServer', x=16.76, y=122.01, z=25.81], EntityArmorStand['§fType §b§l/kitcreator §fto §f§lget items'/742, l='MpServer', x=-8.50, y=124.00, z=8.52], EntityArmorStand['§fType §b§l/kitcreator §fto §f§lget items'/744, l='MpServer', x=8.51, y=124.00, z=-8.51], EntityOtherPlayerMP['wallsfree'/600866, l='MpServer', x=0.00, y=122.00, z=0.00], EntityTippedArrow['Arrow'/601250, l='MpServer', x=-2.97, y=4.66, z=-3.64], EntityOtherPlayerMP['crys5al'/599654, l='MpServer', x=-0.37, y=121.00, z=-20.74], EntityOtherPlayerMP['unluckyGG'/581671, l='MpServer', x=20.68, y=3.00, z=-12.60], EntityOtherPlayerMP['Kildrio'/407987, l='MpServer', x=28.88, y=121.00, z=11.96], EntityOtherPlayerMP['Ratdogg'/593905, l='MpServer', x=4.61, y=4.00, z=8.33], EntityOtherPlayerMP['Beretta3'/599665, l='MpServer', x=23.69, y=2.00, z=-13.30], EntityOtherPlayerMP['P3nisPro'/601265, l='MpServer', x=0.07, y=122.00, z=4.52], EntityOtherPlayerMP['wallsfree'/601267, l='MpServer', x=-0.10, y=122.00, z=1.33], EntityEnderCrystal['entity.EnderCrystal.name'/595062, l='MpServer', x=-34.50, y=5.00, z=12.50]]
	Retry entities: 0 total; []
	Server brand: Crystal (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DriftyDev** [comment]
hole esp glow is not working thats it config issue lmao xD
Glow: None
